#!/usr/bin/env node
// Parses lidl_items.csv → frontend/src/lidlData.js
// Run from matsedel/ directory: node scripts/parse-lidl.js

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const csvPath = resolve(__dirname, '../lidl_items.csv');
// In Docker: COPY frontend/ ./ puts src/ at /build/src/ (not /build/frontend/src/)
// Locally:   script is at matsedel/scripts/, frontend src is at matsedel/frontend/src/
// Detect by checking if ../src exists (Docker) vs ../frontend/src (local)
const dockerSrc = resolve(__dirname, '../src');
const outPath = existsSync(dockerSrc)
  ? resolve(dockerSrc, 'lidlData.js')
  : resolve(__dirname, '../frontend/src/lidlData.js');

const raw = readFileSync(csvPath, 'utf-8').replace(/^\uFEFF/, ''); // strip BOM
const lines = raw.split('\n').map(l => l.trim()).filter(Boolean);
const headers = lines[0].split(';');

function col(row, name) {
  return row[headers.indexOf(name)] ?? '';
}

// Parse all rows
const rows = lines.slice(1).map(line => {
  const row = line.split(';');
  return {
    date: col(row, 'Purchase Date'),
    desc: col(row, 'Item Description'),
    qty: parseFloat(col(row, 'Item Quantity')) || 1,
    unitAmount: parseFloat(col(row, 'Item Unit Amount')) || 0,
    totalAmount: parseFloat(col(row, 'Total Item Amount')) || 0,
  };
});

// Sort by date descending so first occurrence per desc is most recent
rows.sort((a, b) => b.date.localeCompare(a.date));

// Deduplicate — keep most recent row per description
const seen = new Map();
for (const row of rows) {
  if (!seen.has(row.desc)) {
    seen.set(row.desc, row);
  }
}

function parseWeight(desc) {
  // Match patterns like 500g, 1.5kg, 1,5kg, 1l, 33cl, 500ml
  const m = desc.match(/(\d+[\.,]?\d*)\s*(kg|g|l|cl|ml)/i);
  if (!m) return null;
  const val = parseFloat(m[1].replace(',', '.'));
  const unit = m[2].toLowerCase();
  switch (unit) {
    case 'kg': return Math.round(val * 1000);
    case 'g':  return Math.round(val);
    case 'l':  return Math.round(val * 1000);
    case 'cl': return Math.round(val * 10);
    case 'ml': return Math.round(val);
    default:   return null;
  }
}

function isLosvikt(row) {
  // Fractional quantity (not close to whole number) or explicit "lösvikt" in name
  return row.desc.toLowerCase().includes('lösvikt') || (row.qty % 1 > 0.05);
}

const items = [];

for (const [, row] of seen) {
  let weight_g = null;
  let price_kr = 0;

  if (isLosvikt(row)) {
    // qty is in kg, unit_amount is price/kg
    weight_g = Math.round(row.qty * 1000);
    price_kr = parseFloat((row.unitAmount * row.qty).toFixed(2));
  } else {
    // Normal item: qty is count (e.g. 1, 2, 10)
    weight_g = parseWeight(row.desc);
    price_kr = row.unitAmount;
  }

  items.push({
    name: row.desc,
    price_kr,
    weight_g,
    date: row.date,
  });
}

// Sort alphabetically
items.sort((a, b) => a.name.localeCompare(b.name, 'sv'));

const js = `// AUTO-GENERATED by scripts/parse-lidl.js — do not edit manually
export const LIDL_ITEMS = ${JSON.stringify(items, null, 2)};
`;

writeFileSync(outPath, js, 'utf-8');
console.log(`Wrote ${items.length} items to ${outPath}`);
